import { Lead } from "@/components/dashboard/leads/types";

const now = new Date();
const fiveMinutesFromNow = new Date(now.getTime() + 5 * 60 * 1000).toISOString();
const tenMinutesFromNow = new Date(now.getTime() + 10 * 60 * 1000).toISOString();

export const mockLeads: Lead[] = [
    {
        id: 'lead_hot_1',
        name: 'Lead Quente: Cliente de E-commerce de Moda',
        description: 'Dono de e-commerce com faturamento de R$500k/mês buscando agência de tráfego pago para escalar vendas.',
        status: 'hot',
        created_at: now.toISOString(),
        expires_at: fiveMinutesFromNow,
        location: 'São Paulo - SP',
        channel: 'Indicação',
        revenue: 6000000,
        marketingInvestment: 25000,
        companyName: 'Moda Rápida Varejo Online',
        contactName: 'Juliana Paes de Almeida',
        phone: '(11) 91234-5678',
        email: 'juliana.almeida@modarapida.com',
        maskedCompanyName: 'Moda Rápida Varejo ******',
        niche: 'E-commerce de Moda',
        maskedContactName: 'Juliana Paes de ******',
        maskedPhone: '(11) ****-5678',
        maskedEmail: 'j*******@modarapida.com',
        currentBid: 250,
        minimumBid: 100,
        bidders: 7,
        category: 'Marketing Digital',
        tags: ['E-commerce', 'Tráfego Pago', 'Moda'],
    },
    {
        id: 'lead_warm_2',
        name: 'Lead Morno: Clínica Odontológica',
        description: 'Clínica odontológica estabelecida procurando modernizar seu marketing digital e captar pacientes para implantes.',
        status: 'warm',
        created_at: new Date(now.getTime() - 2 * 60 * 1000).toISOString(), // Criado 2 minutos atrás
        expires_at: tenMinutesFromNow,
        location: 'Belo Horizonte - MG',
        channel: 'Google Ads',
        revenue: 1200000,
        marketingInvestment: 5000,
        companyName: 'Sorriso Perfeito Odontologia',
        contactName: 'Dr. Ricardo Mendes',
        phone: '(31) 98765-4321',
        email: 'ricardo.mendes@sorrisoperfeito.com',
        maskedCompanyName: 'Sorriso Perfeito **********',
        niche: 'Saúde / Odontologia',
        maskedContactName: 'Dr. Ricardo ******',
        maskedPhone: '(31) ****-4321',
        maskedEmail: 'r*******@sorrisoperfeito.com',
        currentBid: 80,
        minimumBid: 40,
        bidders: 3,
        category: 'Marketing Digital',
        tags: ['Saúde', 'Google Ads', 'Implantes'],
    },
    {
        id: 'lead_hot_3',
        name: 'Lead Quente: Cliente de E-commerce de Moda',
        description: 'Dono de e-commerce com faturamento de R$500k/mês buscando agência de tráfego pago para escalar vendas.',
        status: 'hot',
        created_at: now.toISOString(),
        expires_at: fiveMinutesFromNow,
        location: 'São Paulo - SP',
        channel: 'Indicação',
        revenue: 6000000,
        marketingInvestment: 25000,
        companyName: 'Moda Rápida Varejo Online',
        contactName: 'Juliana Paes de Almeida',
        phone: '(11) 91234-5678',
        email: 'juliana.almeida@modarapida.com',
        maskedCompanyName: 'Moda Rápida Varejo ******',
        niche: 'E-commerce de Moda',
        maskedContactName: 'Juliana Paes de ******',
        maskedPhone: '(11) ****-5678',
        maskedEmail: 'j*******@modarapida.com',
        currentBid: 250,
        minimumBid: 100,
        bidders: 7,
        category: 'Marketing Digital',
        tags: ['E-commerce', 'Tráfego Pago', 'Moda'],
    },
];
